//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace sunnah.ES
{
    using System;
    using System.Collections.Generic;
    
    public partial class orderedproduct
    {
        public int id { get; set; }
        public Nullable<int> pid { get; set; }
        public Nullable<int> oid { get; set; }
    
        public virtual order order { get; set; }
        public virtual product product { get; set; }
    }
}
